version: "3"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      - /Users/johanque/Documents/Projects/yoga/back_nest_js_type_orm/videos:/usr/src/app/videos 
    command: sh -c 'dockerize -wait tcp://db:3306 -timeout 30s && nodemon -L /usr/src/app/dist/main.js'
  wordpressTer:
    image: wordpress:latest
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: test
      WORDPRESS_DB_NAME: mamazYoga2
      WORDPRESS_TABLE_PREFIX: "mod350_"
    ports:
      - "8082:80"
    volumes:
      - wordpress_data_ter:/var/www/html
      - /Users/johanque/Documents/Projects/yoga/back_nest_js_type_orm/luluzyoga/wp-content:/var/www/html/wp-content
      #- /Users/johanque/Documents/Projects/yoga/back_nest_js_type_orm/luluzyoga/wp-admin:/var/www/html/wp-admin
      #- /Users/johanque/Documents/Projects/yoga/back_nest_js_type_orm/luluzyoga/wp-includes:/var/www/html/wp-includes

volumes:
  dbdata:
  wordpress_data_ter:
